### ISSUE TITLE
Better Filesystem API

### ISSUE THREAD

**Issue by DerekStride** [Shopify/liquid-spec#9]
We need to get explicit Ruby objects out of the specs. @macournoyer suggested a format closer to this:

```yml
filesystem:
    _file1.liquid: {{ content }}
    _file2.liquid: {{ content }}
```
